### ISSUE TITLE
ValueError: invalid literal for int() with base 10: '/m/010016'

### ISSUE THREAD

**Issue by Kamleecoder** [samuelbroscheit/open_knowledge_graph_embeddings#1]
![image](https://user-images.githubusercontent.com/40338036/113095816-c0715f00-9226-11eb-8116-e306e57fb147.png)

**Comment by samuelbroscheit** [comment]
Thanks for reporting I will have a look ASAP!

**Comment by Kamleecoder** [comment]
> Thanks for reporting I will have a look ASAP!

hello samuel. can you tell me what version of python do you use in this work?

**Comment by samuelbroscheit** [comment]
I wrote the code in 3.7, should have specified this.

**Comment by samuelbroscheit** [comment]
This issue was about configurations for Fb15K237 that were not fully functional (and also not necessary for repoducing the OLPBENCH paper). However, now this issue is now adressed with https://github.com/samuelbroscheit/open_knowledge_graph_embeddings/commit/8f5bcc5cfd6554dd382a72516f71d39fb710bb42 . See the instructions https://github.com/samuelbroscheit/open_knowledge_graph_embeddings#use-this-code-for-experiments-on-fb15k237
